name: plain-unit-tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string


jobs:
  run-plain-unit-tests:
    strategy:
      fail-fast: false # Don't cancel all on first failure
      matrix:
        model:
          - "gpt2cpu"
          - "phi2cpu"
          # - "transformers_mistral_7b" See Issue 713
          - "hfllama7b"
          - "hfllama_mistral_7b"
          - "phi3cpu-mini-4k-instruct"

    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        shell: bash
        run: |
           curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.75.0
           echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .[schemas,test]
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install model-specific dependencies
        run: |
          pip install sentencepiece
          pip install "llama-cpp-python!=0.2.58"
      - name: Run tests (except server)
        shell: bash
        run: |
          pytest --cov=guidance --cov-report=xml --cov-report=term-missing \
          --selected_model ${{ matrix.model }} \
          -m "not (needs_credentials or use_gpu or server)" \
          ./tests/
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
