name: Server tests

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      python-version:
        required: true
        type: string

jobs:
  server-tests:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .[all,test]
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run server tests
        shell: bash
        run: |
          pytest --cov=guidance --cov-report=xml --cov-report=term-missing \
          -m server \
          ./tests/

