name: call_server_tests

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      python-version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      os:
        required: false
        type: string
        default: "ubuntu-latest"
      python-version:
        required: false
        type: string
        default: "3.12"
      commit_id:
        description: 'Branch or Commit ID (optional)'
        required: false
        type: string

jobs:
  server_tests:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repo at ${{ github.event_name == 'workflow_dispatch' && inputs.commit_id || github.sha }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.commit_id || github.sha }}
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install guidance in ${{ inputs.os }}
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[all,test]
      - name: server tests
        shell: bash
        run: |
          pytest -vv --cov=guidance --cov-report=xml --cov-report=term-missing \
          ./tests/server
