# CI Tests which run on MacOS machines

# These access secrets, so should only be run on local branches.

# Ideally, the CI tests would be a single workflow, but several issues
# (especially varied OS support) mean that it is hard to keep a single
# workflow green.

# MacOS has been a particular trouble due to the small disk space
# allocations on all the VMs, leading to the --selected_model
# machinery

name: CI Tests - MacOS
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Branch or Commit ID (optional)'
        required: false
        type: string
  schedule:
    # * is a special character in YAML so we quote this string
    # Run at 09:10 UTC every day
    - cron:  '10 09 * * *'

jobs:
  cpu_small:
    strategy:
      fail-fast: false # Don't cancel all on first failure
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        model:
          - "transformers_gpt2_cpu"
          - "llamacpp_phi3_mini_4k_instruct_cpu"
          - "llamacpp_gemma2_9b_cpu"
    uses: ./.github/workflows/call_cpu_tests.yml
    with:
      os: "macos-latest"
      python-version: ${{ matrix.python-version }}
      model: ${{ matrix.model }}
    secrets:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}