name: Unit tests GPU

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  unit-tests-gpu:

    strategy:
      fail-fast: false # Don't cancel all on first failure
      matrix:
        os: [gpu-runner]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        model: ["gpt2gpu", "phi2gpu", "hfllama_7b_gpu"]
    uses: ./.github/workflows/template_unit_tests_on_gpu.yml
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python-version }}
      model: ${{ matrix.model }}